osx_image: xcode8
language: objective-c
cache: cocoapods
before_install: pod update
script: xcodebuild -workspace Demo.xcworkspace -scheme Tests -sdk iphonesimulator test | xcpretty -c && exit ${PIPESTATUS[0]}
